//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationOption
    {
        public int id { get; set; }
        public Nullable<int> reservation_id { get; set; }
        public Nullable<int> option_id { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual ExtraOption ExtraOption { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
